name: Selenium Pytest with Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Run pytest with Allure results
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure HTML report
      uses: simple-elf/allure-report-action@v1.7
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
